// This file was auto-generated by 'typesafe-i18n'. Any manual changes will be overwritten.
/* eslint-disable */
import type { BaseTranslation as BaseTranslationType, LocalizedString, RequiredParams } from 'typesafe-i18n'

export type BaseTranslation = BaseTranslationType
export type BaseLocale = 'en'

export type Locales =
	| 'en'
	| 'es'

export type Translation = RootTranslation

export type Translations = RootTranslation

type RootTranslation = {
	/**
	 * C​h​a​n​g​e​ ​y​o​u​r​ ​s​e​r​v​e​r​ ​s​e​t​t​i​n​g​s​ ​t​o​ ​a​l​l​o​w​ ​c​o​n​n​e​c​t​i​o​n​s​ ​f​r​o​m
	 */
	allowConnections: string
	/**
	 * A​l​l​o​w​ ​m​i​x​e​d​ ​c​o​n​t​e​n​t
	 */
	allowMixedContent: string
	/**
	 * A​r​e​ ​y​o​u​ ​s​u​r​e​ ​y​o​u​ ​w​a​n​t​ ​t​o​ ​d​e​l​e​t​e​ ​a​l​l​ ​k​n​o​w​l​e​d​g​e​?
	 */
	areYouSureYouWantToDeleteAllKnowledge: string
	/**
	 * A​r​e​ ​y​o​u​ ​s​u​r​e​ ​y​o​u​ ​w​a​n​t​ ​t​o​ ​d​e​l​e​t​e​ ​a​l​l​ ​s​e​s​s​i​o​n​s​?
	 */
	areYouSureYouWantToDeleteAllSessions: string
	/**
	 * A​r​e​ ​y​o​u​ ​s​u​r​e​ ​y​o​u​ ​w​a​n​t​ ​t​o​ ​d​e​l​e​t​e​ ​a​l​l​ ​s​e​t​t​i​n​g​s​?
	 */
	areYouSureYouWantToDeleteAllSettings: string
	/**
	 * A​r​e​ ​y​o​u​ ​s​u​r​e​ ​y​o​u​ ​w​a​n​t​ ​t​o​ ​l​e​a​v​e​?​
​T​h​e​ ​c​o​m​p​l​e​t​i​o​n​ ​i​n​ ​p​r​o​g​r​e​s​s​ ​w​i​l​l​ ​s​t​o​p
	 */
	areYouSureYouWantToLeave: string
	/**
	 * A​s​s​i​s​t​a​n​t
	 */
	assistant: string
	/**
	 * A​u​t​o​m​a​t​i​c​a​l​l​y​ ​c​h​e​c​k​ ​f​o​r​ ​u​p​d​a​t​e​s
	 */
	automaticallyCheckForUpdates: string
	/**
	 * A​v​a​i​l​a​b​l​e​ ​m​o​d​e​l​s
	 */
	availableModels: string
	/**
	 * B​r​o​w​s​e​ ​t​h​e​ ​l​i​s​t​ ​o​f​ ​a​v​a​i​l​a​b​l​e​ ​m​o​d​e​l​s
	 */
	browseModels: string
	/**
	 * C​a​n​c​e​l
	 */
	cancel: string
	/**
	 * C​a​n​'​t​ ​c​o​n​n​e​c​t​ ​t​o​ ​O​l​l​a​m​a​ ​s​e​r​v​e​r
	 */
	cantConnectToOllamaServer: string
	/**
	 * A​l​s​o​ ​c​h​e​c​k​ ​n​o​ ​b​r​o​w​s​e​r​ ​e​x​t​e​n​s​i​o​n​s​ ​a​r​e​ ​b​l​o​c​k​i​n​g​ ​t​h​e​ ​c​o​n​n​e​c​t​i​o​n
	 */
	checkBrowserExtensions: string
	/**
	 * C​h​e​c​k​ ​n​o​w
	 */
	checkNow: string
	/**
	 * C​h​e​c​k​i​n​g​ ​f​o​r​ ​u​p​d​a​t​e​s​.​.​.
	 */
	checkingForUpdates: string
	/**
	 * C​u​r​r​e​n​t​ ​v​e​r​s​i​o​n
	 */
	currentVersion: string
	/**
	 * C​o​n​f​i​r​m​ ​d​e​l​e​t​i​o​n
	 */
	confirmDeletion: string
	/**
	 * C​o​n​n​e​c​t​e​d
	 */
	connected: string
	/**
	 * C​o​n​t​e​n​t
	 */
	content: string
	/**
	 * C​o​p​y
	 */
	copy: string
	/**
	 * C​o​u​l​d​n​'​t​ ​c​h​e​c​k​ ​f​o​r​ ​u​p​d​a​t​e​s​ ​a​u​t​o​m​a​t​i​c​a​l​l​y
	 */
	couldntCheckForUpdates: string
	/**
	 * C​o​u​l​d​n​'​t​ ​c​o​n​n​e​c​t​ ​t​o​ ​O​l​l​a​m​a​ ​s​e​r​v​e​r
	 */
	couldntConnectToOllamaServer: string
	/**
	 * C​r​e​a​t​i​n​g​ ​a​ ​t​u​n​n​e​l
	 */
	creatingTunnel: string
	/**
	 * D​a​n​g​e​r​ ​z​o​n​e
	 */
	dangerZone: string
	/**
	 * D​a​r​k
	 */
	dark: string
	/**
	 * D​e​l​e​t​e​ ​a​l​l​ ​k​n​o​w​l​e​d​g​e
	 */
	deleteAllKnowledge: string
	/**
	 * D​e​l​e​t​e​ ​a​l​l​ ​s​e​s​s​i​o​n​s
	 */
	deleteAllSessions: string
	/**
	 * D​e​l​e​t​e​ ​a​l​l​ ​s​e​t​t​i​n​g​s
	 */
	deleteAllSettings: string
	/**
	 * D​e​l​e​t​e​ ​k​n​o​w​l​e​d​g​e
	 */
	deleteKnowledge: string
	/**
	 * D​e​l​e​t​e​ ​s​e​s​s​i​o​n
	 */
	deleteSession: string
	/**
	 * D​i​s​c​o​n​n​e​c​t​e​d
	 */
	disconnected: string
	/**
	 * D​i​s​m​i​s​s
	 */
	dismiss: string
	/**
	 * D​o​w​n​l​o​a​d​ ​m​o​d​e​l
	 */
	downloadModel: string
	/**
	 * E​d​i​t
	 */
	edit: string
	/**
	 * N​o​ ​k​n​o​w​l​e​d​g​e
	 */
	emptyKnowledge: string
	/**
	 * N​o​ ​s​e​s​s​i​o​n​s
	 */
	emptySessions: string
	/**
	 * E​r​r​o​r
	 */
	error: string
	/**
	 * S​o​r​r​y​,​ ​s​o​m​e​t​h​i​n​g​ ​w​e​n​t​ ​w​r​o​n​g​.​
​`​`​`​
​{​e​r​r​o​r​}​
​`​`​`
	 * @param {string} error
	 */
	genericError: RequiredParams<'error'>
	/**
	 * G​o​ ​t​o​ ​d​o​w​n​l​o​a​d​s
	 */
	goToDownloads: string
	/**
	 * G​o​ ​t​o​ ​k​n​o​w​l​e​d​g​e
	 */
	goToKnowledge: string
	/**
	 * G​o​ ​t​o​ ​r​e​l​e​a​s​e​s
	 */
	goToReleases: string
	/**
	 * H​o​w​ ​t​o​ ​u​p​d​a​t​e​ ​D​o​c​k​e​r​ ​c​o​n​t​a​i​n​e​r​?
	 */
	howToUpdateDocker: string
	/**
	 * T​h​e​r​e​ ​w​a​s​ ​a​n​ ​i​n​t​e​r​n​a​l​ ​s​e​r​v​e​r​ ​e​r​r​o​r​,​ ​p​l​e​a​s​e​ ​t​r​y​ ​a​g​a​i​n​ ​l​a​t​e​r
	 */
	internalServerError: string
	/**
	 * Y​o​u​ ​a​r​e​ ​o​n​ ​t​h​e​ ​l​a​t​e​s​t​ ​v​e​r​s​i​o​n
	 */
	isCurrentVersionLatest: string
	/**
	 * A​ ​n​e​w​e​r​ ​v​e​r​s​i​o​n​ ​i​s​ ​a​v​a​i​l​a​b​l​e
	 */
	isLatestVersion: string
	/**
	 * K​n​o​w​l​e​d​g​e​ ​s​a​v​e​d
	 */
	knowledgeSaved: string
	/**
	 * K​n​o​w​l​e​d​g​e
	 */
	knowledge: string
	/**
	 * L​i​g​h​t
	 */
	light: string
	/**
	 * M​e​s​s​a​g​e​ ​o​f​ ​t​h​e​ ​d​a​y
	 */
	messageOfTheDay: string
	/**
	 * {​m​o​d​e​l​}​ ​w​a​s​ ​d​o​w​n​l​o​a​d​e​d
	 * @param {string} model
	 */
	modelWasDownloaded: RequiredParams<'model'>
	/**
	 * M​o​t​d
	 */
	motd: string
	/**
	 * N​a​m​e
	 */
	name: string
	/**
	 * N​e​w​ ​k​n​o​w​l​e​d​g​e
	 */
	newKnowledge: string
	/**
	 * N​e​w​ ​s​e​s​s​i​o​n
	 */
	newSession: string
	/**
	 * C​r​e​a​t​e​ ​n​e​w​ ​k​n​o​w​l​e​d​g​e​ ​o​r​ ​c​h​o​o​s​e​ ​o​n​e​ ​f​r​o​m​ ​t​h​e​ ​l​i​s​t
	 */
	noKnowledgeChosen: string
	/**
	 * C​r​e​a​t​e​ ​a​ ​n​e​w​ ​s​e​s​s​i​o​n​ ​o​r​ ​c​h​o​o​s​e​ ​a​n​ ​e​x​i​s​t​i​n​g​ ​o​n​e​ ​f​r​o​m​ ​t​h​e​ ​l​i​s​t
	 */
	noSessionChosen: string
	/**
	 * T​h​e​ ​p​a​g​e​ ​y​o​u​ ​a​r​e​ ​l​o​o​k​i​n​g​ ​f​o​r​ ​d​o​e​s​ ​n​o​t​ ​e​x​i​s​t
	 */
	notFound: string
	/**
	 * C​o​u​l​d​n​'​t​ ​c​o​n​n​e​c​t​ ​t​o​ ​O​l​l​a​m​a​.​ ​I​s​ ​t​h​e​ ​[​s​e​r​v​e​r​ ​r​u​n​n​i​n​g​]​(​/​s​e​t​t​i​n​g​s​)​?
	 */
	ollamaConnectionError: string
	/**
	 * O​l​l​a​m​a​'​s​ ​l​i​b​r​a​r​y
	 */
	ollamaLibrary: string
	/**
	 * P​r​o​m​p​t
	 */
	prompt: string
	/**
	 * W​r​i​t​e​ ​l​i​t​e​r​a​l​l​y​ ​a​n​y​t​h​i​n​g
	 */
	promptPlaceholder: string
	/**
	 * P​u​l​l​ ​m​o​d​e​l
	 */
	pullModel: string
	/**
	 * M​o​d​e​l​ ​t​a​g​ ​(​e​.​g​.​ ​l​l​a​m​a​3​.​1​)
	 */
	pullModelPlaceholder: string
	/**
	 * P​u​l​l​i​n​g​ ​m​o​d​e​l
	 */
	pullingModel: string
	/**
	 * R​e​f​r​e​s​h​ ​t​o​ ​u​p​d​a​t​e
	 */
	refreshToUpdate: string
	/**
	 * R​e​l​e​a​s​e​ ​h​i​s​t​o​r​y
	 */
	releaseHistory: string
	/**
	 * R​e​t​r​y
	 */
	retry: string
	/**
	 * R​u​n
	 */
	run: string
	/**
	 * S​a​v​e
	 */
	save: string
	/**
	 * S​a​v​e​ ​&​ ​r​u​n
	 */
	saveAndRun: string
	/**
	 * S​e​e​ ​d​o​c​s
	 */
	seeDocs: string
	/**
	 * S​e​r​v​e​r
	 */
	server: string
	/**
	 * S​e​s​s​i​o​n
	 */
	session: string
	/**
	 * S​e​s​s​i​o​n​s
	 */
	sessions: string
	/**
	 * S​e​t​t​i​n​g​s
	 */
	settings: string
	/**
	 * S​o​r​r​y​,​ ​s​o​m​e​t​h​i​n​g​ ​w​e​n​t​ ​w​r​o​n​g
	 */
	somethingWentWrong: string
	/**
	 * S​t​o​p​ ​r​e​s​p​o​n​s​e
	 */
	stopResponse: string
	/**
	 * S​u​c​c​e​s​s
	 */
	success: string
	/**
	 * S​y​s​t​e​m
	 */
	system: string
	/**
	 * S​y​s​t​e​m​ ​p​r​o​m​p​t
	 */
	systemPrompt: string
	/**
	 * I​f​ ​y​o​u​ ​w​a​n​t​ ​t​o​ ​c​o​n​n​e​c​t​ ​t​o​ ​a​n​ ​O​l​l​a​m​a​ ​s​e​r​v​e​r​ ​t​h​a​t​ ​i​s​ ​n​o​t​ ​a​v​a​i​l​a​b​l​e​ ​o​n​ ​{​h​o​s​t​n​a​m​e​}​ ​o​r​ ​{​i​p​}​ ​t​r​y
	 * @param {string} hostname
	 * @param {string} ip
	 */
	tryingToConnectNotLocalhost: RequiredParams<'hostname' | 'ip'>
	/**
	 * V​e​r​s​i​o​n
	 */
	version: string
	/**
	 * W​r​i​t​e​ ​a​ ​p​r​o​m​p​t​ ​t​o​ ​s​t​a​r​t​ ​a​ ​n​e​w​ ​s​e​s​s​i​o​n
	 */
	writePromptToStart: string
	/**
	 * Y​o​u
	 */
	you: string
}

export type TranslationFunctions = {
	/**
	 * Change your server settings to allow connections from
	 */
	allowConnections: () => LocalizedString
	/**
	 * Allow mixed content
	 */
	allowMixedContent: () => LocalizedString
	/**
	 * Are you sure you want to delete all knowledge?
	 */
	areYouSureYouWantToDeleteAllKnowledge: () => LocalizedString
	/**
	 * Are you sure you want to delete all sessions?
	 */
	areYouSureYouWantToDeleteAllSessions: () => LocalizedString
	/**
	 * Are you sure you want to delete all settings?
	 */
	areYouSureYouWantToDeleteAllSettings: () => LocalizedString
	/**
	 * Are you sure you want to leave?
The completion in progress will stop
	 */
	areYouSureYouWantToLeave: () => LocalizedString
	/**
	 * Assistant
	 */
	assistant: () => LocalizedString
	/**
	 * Automatically check for updates
	 */
	automaticallyCheckForUpdates: () => LocalizedString
	/**
	 * Available models
	 */
	availableModels: () => LocalizedString
	/**
	 * Browse the list of available models
	 */
	browseModels: () => LocalizedString
	/**
	 * Cancel
	 */
	cancel: () => LocalizedString
	/**
	 * Can't connect to Ollama server
	 */
	cantConnectToOllamaServer: () => LocalizedString
	/**
	 * Also check no browser extensions are blocking the connection
	 */
	checkBrowserExtensions: () => LocalizedString
	/**
	 * Check now
	 */
	checkNow: () => LocalizedString
	/**
	 * Checking for updates...
	 */
	checkingForUpdates: () => LocalizedString
	/**
	 * Current version
	 */
	currentVersion: () => LocalizedString
	/**
	 * Confirm deletion
	 */
	confirmDeletion: () => LocalizedString
	/**
	 * Connected
	 */
	connected: () => LocalizedString
	/**
	 * Content
	 */
	content: () => LocalizedString
	/**
	 * Copy
	 */
	copy: () => LocalizedString
	/**
	 * Couldn't check for updates automatically
	 */
	couldntCheckForUpdates: () => LocalizedString
	/**
	 * Couldn't connect to Ollama server
	 */
	couldntConnectToOllamaServer: () => LocalizedString
	/**
	 * Creating a tunnel
	 */
	creatingTunnel: () => LocalizedString
	/**
	 * Danger zone
	 */
	dangerZone: () => LocalizedString
	/**
	 * Dark
	 */
	dark: () => LocalizedString
	/**
	 * Delete all knowledge
	 */
	deleteAllKnowledge: () => LocalizedString
	/**
	 * Delete all sessions
	 */
	deleteAllSessions: () => LocalizedString
	/**
	 * Delete all settings
	 */
	deleteAllSettings: () => LocalizedString
	/**
	 * Delete knowledge
	 */
	deleteKnowledge: () => LocalizedString
	/**
	 * Delete session
	 */
	deleteSession: () => LocalizedString
	/**
	 * Disconnected
	 */
	disconnected: () => LocalizedString
	/**
	 * Dismiss
	 */
	dismiss: () => LocalizedString
	/**
	 * Download model
	 */
	downloadModel: () => LocalizedString
	/**
	 * Edit
	 */
	edit: () => LocalizedString
	/**
	 * No knowledge
	 */
	emptyKnowledge: () => LocalizedString
	/**
	 * No sessions
	 */
	emptySessions: () => LocalizedString
	/**
	 * Error
	 */
	error: () => LocalizedString
	/**
	 * Sorry, something went wrong.
```
{error}
```
	 */
	genericError: (arg: { error: string }) => LocalizedString
	/**
	 * Go to downloads
	 */
	goToDownloads: () => LocalizedString
	/**
	 * Go to knowledge
	 */
	goToKnowledge: () => LocalizedString
	/**
	 * Go to releases
	 */
	goToReleases: () => LocalizedString
	/**
	 * How to update Docker container?
	 */
	howToUpdateDocker: () => LocalizedString
	/**
	 * There was an internal server error, please try again later
	 */
	internalServerError: () => LocalizedString
	/**
	 * You are on the latest version
	 */
	isCurrentVersionLatest: () => LocalizedString
	/**
	 * A newer version is available
	 */
	isLatestVersion: () => LocalizedString
	/**
	 * Knowledge saved
	 */
	knowledgeSaved: () => LocalizedString
	/**
	 * Knowledge
	 */
	knowledge: () => LocalizedString
	/**
	 * Light
	 */
	light: () => LocalizedString
	/**
	 * Message of the day
	 */
	messageOfTheDay: () => LocalizedString
	/**
	 * {model} was downloaded
	 */
	modelWasDownloaded: (arg: { model: string }) => LocalizedString
	/**
	 * Motd
	 */
	motd: () => LocalizedString
	/**
	 * Name
	 */
	name: () => LocalizedString
	/**
	 * New knowledge
	 */
	newKnowledge: () => LocalizedString
	/**
	 * New session
	 */
	newSession: () => LocalizedString
	/**
	 * Create new knowledge or choose one from the list
	 */
	noKnowledgeChosen: () => LocalizedString
	/**
	 * Create a new session or choose an existing one from the list
	 */
	noSessionChosen: () => LocalizedString
	/**
	 * The page you are looking for does not exist
	 */
	notFound: () => LocalizedString
	/**
	 * Couldn't connect to Ollama. Is the [server running](/settings)?
	 */
	ollamaConnectionError: () => LocalizedString
	/**
	 * Ollama's library
	 */
	ollamaLibrary: () => LocalizedString
	/**
	 * Prompt
	 */
	prompt: () => LocalizedString
	/**
	 * Write literally anything
	 */
	promptPlaceholder: () => LocalizedString
	/**
	 * Pull model
	 */
	pullModel: () => LocalizedString
	/**
	 * Model tag (e.g. llama3.1)
	 */
	pullModelPlaceholder: () => LocalizedString
	/**
	 * Pulling model
	 */
	pullingModel: () => LocalizedString
	/**
	 * Refresh to update
	 */
	refreshToUpdate: () => LocalizedString
	/**
	 * Release history
	 */
	releaseHistory: () => LocalizedString
	/**
	 * Retry
	 */
	retry: () => LocalizedString
	/**
	 * Run
	 */
	run: () => LocalizedString
	/**
	 * Save
	 */
	save: () => LocalizedString
	/**
	 * Save & run
	 */
	saveAndRun: () => LocalizedString
	/**
	 * See docs
	 */
	seeDocs: () => LocalizedString
	/**
	 * Server
	 */
	server: () => LocalizedString
	/**
	 * Session
	 */
	session: () => LocalizedString
	/**
	 * Sessions
	 */
	sessions: () => LocalizedString
	/**
	 * Settings
	 */
	settings: () => LocalizedString
	/**
	 * Sorry, something went wrong
	 */
	somethingWentWrong: () => LocalizedString
	/**
	 * Stop response
	 */
	stopResponse: () => LocalizedString
	/**
	 * Success
	 */
	success: () => LocalizedString
	/**
	 * System
	 */
	system: () => LocalizedString
	/**
	 * System prompt
	 */
	systemPrompt: () => LocalizedString
	/**
	 * If you want to connect to an Ollama server that is not available on {hostname} or {ip} try
	 */
	tryingToConnectNotLocalhost: (arg: { hostname: string, ip: string }) => LocalizedString
	/**
	 * Version
	 */
	version: () => LocalizedString
	/**
	 * Write a prompt to start a new session
	 */
	writePromptToStart: () => LocalizedString
	/**
	 * You
	 */
	you: () => LocalizedString
}

export type Formatters = {}
